name: CI

on: [push]

jobs:
  jax_transforms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements-jax_transforms-test.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          python -m pip install -r requirements-jax_transforms-test.txt
      - name: Install CmdStan
        run: |
          import cmdstanpy
          cmdstanpy.install_cmdstan()
        shell: python
      - name: Test with pytest
        run: pytest jax_transforms/
