name: CI

on: [push]
  
jobs:
  jax_transforms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pytest
          python -m pip install -r requirements-jax_transforms.txt
      - name: Test with pytest
        run: pytest jax_transforms/